### ISSUE TITLE
Ecto repo not started for LiveView

### ISSUE THREAD

**Issue by nileshtrivedi** [phoenix-playground/phoenix_playground#19]
I wanted to experiment with a complete todo list app with PhoenixPlayground - with a database and JWT based user-authentication. Here is what I came up with:

```
Mix.install([
  {:phoenix_playground, "~> 0.1.6"},
  {:phoenix_ecto, "== 4.6.3"},
  {:ecto_sql, "== 3.12.1"},
  {:postgrex, "== 0.19.3"},
  {:jason, "~> 1.4"},
  {:jose, "~> 1.11"}
])

# Database configuration
db_url = "postgres://postgres@localhost:5432/postgres"

# Repository setup
defmodule MyRepo do
  use Ecto.Repo,
    otp_app: :learn,
    adapter: Ecto.Adapters.Postgres
end

# Start the repository
MyRepo.start_link(url: db_url, ssl: false)

defmodule Todo do
  use Ecto.Schema

  schema "todos" do
    field :name, :string
    field :status, :string, default: "pending"
    field :user_id, :string
    timestamps()
  end

  def changeset(todo, attrs \\ %{}) do
    todo
    |> Ecto.Changeset.cast(attrs, [:name, :status, :user_id])
    |> Ecto.Changeset.validate_required([:name, :user_id])
    |> Ecto.Changeset.validate_format(:user_id, ~r/^[\w-]+$/, message: "Invalid user ID")
  end
end

defmodule Migrations do
  def migrate do
    create_todos_table()
  end

  defp create_todos_table do
    MyRepo.query!("""
    CREATE TABLE IF NOT EXISTS todos (
      id SERIAL PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      status VARCHAR(20) DEFAULT 'pending',
      user_id VARCHAR(255) NOT NULL,
      inserted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """)
  end
end

Migrations.migrate()

defmodule AuthPlug do
  import Plug.Conn

  def init(opts), do: opts

  def call(conn, _opts) do
    IO.inspect "Authenticating..."
    case get_jwt(conn) do
      {:ok, jwt} ->
        case verify_token(jwt) do
          {:ok, user_id} ->
            conn
            |> put_resp_cookie("jwt", jwt)
            |> assign(:user_id, user_id)

          {:error, _reason} ->
            unauthorized(conn)
        end

      :error ->
        unauthorized(conn)
    end
  end

  defp get_jwt(conn) do
    # Extract JWT first from cookies, then from query parameter
    jwt = conn.cookies["jwt"] || conn.query_params["jwt"]
    if jwt != nil do
      {:ok, jwt}
    else
      :error
    end
  end

  defp unauthorized(conn) do
    conn
    |> put_resp_content_type("text/plain")
    |> send_resp(401, "Unauthorized")
    |> halt()
  end

  # Validate and decode the token, extracting user_id
  defp verify_token(jwt) do
    jwk =  %{
      "kty" => "oct",
      "k" => :jose_base64url.encode(System.get_env("JWT_SECRET"))
    }

    case JOSE.JWT.verify_strict(jwk, ["HS256"], jwt) do
      {true, claims, _} -> {:ok, claims.fields["sub"]}
      _ -> :error
    end
  end
end

  # Router setup
defmodule CustomRouter do
  use Phoenix.Router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :put_secret_key_base
    plug :fetch_cookies
    plug :fetch_query_params
    plug :fetch_session
    plug AuthPlug
    plug :put_root_layout, html: {PhoenixPlayground.Layout, :root}
    plug :put_secure_browser_headers
  end

  scope "/" do
    pipe_through :browser
    live "/", TodoLive, :index
  end

  def put_secret_key_base(conn, _) do
    put_in conn.secret_key_base, System.get_env("SECRET_KEY_BASE")
  end
end

# Todo LiveView
defmodule TodoLive do
  use Phoenix.LiveView
  import Ecto.Query

  def get_user_todos(user_id) do
    MyRepo.all(from t in Todo, where: t.user_id == ^user_id)
  end

  def mount(_params, %{"user_id" => user_id} = session, socket) do
    session |> dbg
    socket.assigns |> dbg

    user_id = "testuser"

    if user_id == nil do
      # cannot render, handle error with a flash message
      {:error, "You must be logged in to view this page"}
    else
      {:ok, assign(socket,
        user_id: user_id,
        new_todo_name: "new task",
        todos: get_user_todos(user_id)
      )}
    end
  end

  def render(assigns) do
    ~H"""
    <div class="max-w-md mx-auto mt-10 p-6 bg-white rounded-lg shadow-md">
      <h1 class="text-2xl font-bold mb-4">Todo List for <%= @user_id %></h1>

      <form phx-submit="create_todo" class="mb-4 flex">
        <input
          type="text"
          name="name"
          value={@new_todo_name}
          placeholder="Enter a new todo"
          class="flex-grow mr-2 px-2 py-1 border rounded"
        />
        <button
          type="submit"
          class="bg-blue-500 text-white px-4 py-1 rounded hover:bg-blue-600"
        >
          Add Todo
        </button>
      </form>

      <ul>
        <%= for todo <- @todos do %>
          <li class="flex items-center justify-between py-2 border-b">
            <label class="flex items-center">
              <input
                type="checkbox"
                phx-click="toggle_todo"
                phx-value-id={todo.id}
                checked={todo.status == "done"}
                class="mr-2"
              />
              <span class={if todo.status == "done", do: "line-through text-gray-500", else: ""}>
                <%= todo.name %>
              </span>
            </label>
            <button
              phx-click="delete_todo"
              phx-value-id={todo.id}
              class="text-red-500 hover:text-red-700"
            >
              ✕
            </button>
          </li>
        <% end %>
      </ul>
    </div>
    """
  end

  def handle_event("create_todo", %{"name" => name}, socket) do
    # Trim and validate todo name
    name = String.trim(name)

    if name == "" do
      {:noreply, socket}
    else
      # Create new todo with current user's ID
      {:ok, _todo} =
        %Todo{}
        |> Todo.changeset(%{
          name: name,
          user_id: socket.assigns.user_id
        })
        |> MyRepo.insert()

      # Update socket with new list of todos
      socket =
        socket
        |> assign(:todos, get_user_todos(socket.assigns.user_id))
        |> assign(:new_todo_name, "")

      {:noreply, socket}
    end
  end

  def handle_event("toggle_todo", %{"id" => id}, socket) do
    # Find the todo and ensure it belongs to current user
    todo = MyRepo.get_by!(Todo, [id: id, user_id: socket.assigns.user_id])

    # Toggle status
    new_status = if todo.status == "pending", do: "done", else: "pending"

    # Update todo
    {:ok, _todo} =
      todo
      |> Todo.changeset(%{status: new_status})
      |> MyRepo.update()

    # Refresh todos
    {:noreply, assign(socket, :todos, get_user_todos(socket.assigns.user_id))}
  end

  def handle_event("delete_todo", %{"id" => id}, socket) do
    # Delete todo, ensuring it belongs to current user
    todo = MyRepo.get_by!(Todo, [id: id, user_id: socket.assigns.user_id])
    MyRepo.delete(todo)

    # Refresh todos
    {:noreply, assign(socket, :todos, get_user_todos(socket.assigns.user_id))}
  end
end

PhoenixPlayground.start(plug: CustomRouter, live_reload: false, open_browser: false)
```

I start it with: `JWT_SECRET=6fa91f11ca785e9a73d340ea8d3d03ed SECRET_KEY_BASE=6fa91f11ca785e9a73d340ea8d3d03ed6fa91f11ca785e9a73d340ea8d3d03ed elixir app.exs`

But despite running the migration file upon start, I get this error:

```
13:58:04.940 [info] Running PhoenixPlayground.Endpoint with Bandit 1.6.1 at 127.0.0.1:4000 (http)

13:58:04.940 [info] Access PhoenixPlayground.Endpoint at http://localhost:4000

13:58:15.411 [info] GET /

13:58:15.417 [debug] Processing with TodoLive.index/2
  Parameters: %{}
  Pipelines: [:browser]
"Authenticating..."
[app.exs:153: TodoLive.mount/3]
session #=> %{"user_id" => "1234567890"}

[app.exs:154: TodoLive.mount/3]
socket.assigns #=> %{flash: %{}, __changed__: %{}, live_action: :index}


13:58:15.451 [info] Sent 500 in 39ms

13:58:15.452 [error] ** (RuntimeError) could not lookup Ecto repo MyRepo because it was not started or it does not exist
    (ecto 3.12.5) lib/ecto/repo/registry.ex:22: Ecto.Repo.Registry.lookup/1
    (ecto 3.12.5) lib/ecto/repo/supervisor.ex:176: Ecto.Repo.Supervisor.tuplet/2
    app.exs:15: MyRepo.all/2
    app.exs:165: TodoLive.mount/3
    (phoenix_live_view 1.0.0) lib/phoenix_live_view/utils.ex:348: anonymous fn/6 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/5
    (telemetry 1.3.0) /Users/nt/Library/Caches/mix/installs/elixir-1.17.3-erts-15.1.2/cb2a51975586ec4cae9addab4e30610a/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
    (phoenix_live_view 1.0.0) lib/phoenix_live_view/static.ex:320: Phoenix.LiveView.Static.call_mount_and_handle_params!/5
    (phoenix_live_view 1.0.0) lib/phoenix_live_view/static.ex:155: Phoenix.LiveView.Static.do_render/4
```

I suspect `MyRepo` is not being made available to LiveView processes but I don't under Phoenix internals well enough to debug it further.

**Comment by wojtekmach** [comment]
Try adding :child_specs option with your repo to PhoenixPlayground.start/1. Let me know how that goes!

**Comment by nileshtrivedi** [comment]
Thanks @wojtekmach . This works:

```
Mix.install([
  {:phoenix_playground, "== 0.1.6"},
  {:phoenix_ecto, "== 4.6.3"},
  {:ecto_sql, "== 3.12.1"},
  {:postgrex, "== 0.19.3"}
])

defmodule MyRepo do
  use Ecto.Repo, otp_app: :myapp, adapter: Ecto.Adapters.Postgres
end

Application.put_env(:myapp, MyRepo,
  database: "postgres",
  username: "postgres",
  password: "",
  hostname: "localhost",
  port: 5432
)

{:ok, _} = Application.ensure_all_started(:postgrex)
{:ok, _} = Application.ensure_all_started(:ecto)

PhoenixPlayground.start(
  open_browser: false,
  live_reload: false,
  child_specs: [
    {MyRepo, []}
  ],
  plug: fn conn ->
    todo_count = MyRepo.aggregate("todos", :count)
    Plug.Conn.send_resp(conn, 200, "There are #{todo_count} todos!")
  end
)

```
